#!/usr/bin/env node
import {readFile,writeFile,mkdir,rename,unlink} from 'node:fs/promises'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import vm from 'node:vm'
import {transform,targets,optionalTargets,resources} from './bridge/transform.mjs'
const hash=value=>createHash('sha256').update(value).digest('hex');
const own=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(process.argv[2]||'');
const backup=path.join(root,'.message-actions-preview-v1');
const manifestPath=path.join(backup,'manifest.json');
const apply=process.argv.includes('--apply'),restore=process.argv.includes('--restore');
if(!process.argv[2])throw new Error('用法：node install-bridge.mjs <DSHT 源码根目录> [--apply | --restore]；默认仅检查');
async function atomic(file,data){const temp=file+'.message-actions.tmp';await mkdir(path.dirname(file),{recursive:true});await writeFile(temp,data);try{await rename(temp,file);}finally{await unlink(temp).catch(()=>{});}}
const manifest=await readFile(manifestPath,'utf8').then(JSON.parse).catch(error=>{if(error.code==='ENOENT')return null;throw error;});
if(manifest){
  if(manifest.root!==root||manifest.version!==1)throw new Error('桥接备份身份不匹配');
  for(const entry of manifest.files){
    if(![...targets,...optionalTargets,'tavern-plugin/lib/client.js',...resources.map(row=>row[0])].includes(entry.file))throw new Error('备份清单含未知文件');
    if(hash(await readFile(path.join(root,entry.file)))!==entry.installedHash)throw new Error('安装后源码已变化，停止覆盖或恢复：'+entry.file);
    if(entry.existed&&hash(await readFile(path.join(backup,entry.file)))!==entry.originalHash)throw new Error('备份校验失败：'+entry.file);
  }
  if(restore){
    for(const entry of manifest.files){const file=path.join(root,entry.file);if(entry.existed)await atomic(file,await readFile(path.join(backup,entry.file)));else await unlink(file);}
    await rename(manifestPath,path.join(backup,'restored-'+Date.now()+'.json'));
    console.log('已恢复桥接前源码；插件包请另行停用。未触及存档。');
  }else console.log('桥接已安装，全部文件哈希核对通过；未重复修改。');
}else{
  if(restore)throw new Error('没有可恢复的桥接清单');
  const output=new Map(),original=new Map();
  for(const file of targets){const bytes=await readFile(path.join(root,file));original.set(file,bytes);output.set(file,transform(file,bytes.toString('utf8')));}
  if(original.get('tavern-plugin/lib/index.js').toString('utf8').includes('const pluginData = createPluginData(')) {
    for(const file of optionalTargets){const bytes=await readFile(path.join(root,file));original.set(file,bytes);output.set(file,transform(file,bytes.toString('utf8')));}
  }
  for(const [target,resource] of resources){
    const old=await readFile(path.join(root,target)).catch(error=>{if(error.code==='ENOENT')return null;throw error;});
    const data=await readFile(path.join(own,resource),'utf8');
    // Development copy may already contain exactly this new module.
    if(old&&old.toString('utf8').replace(/\r\n/g,'\n')!==data.replace(/\r\n/g,'\n'))throw new Error('桥接新文件已存在且内容不同：'+target);
    original.set(target,old);output.set(target,data);
  }
  const include=/^([\t ]*)\/\/ @include(-domain)? ([a-zA-Z0-9._/-]+)[\t ]*$/gm;
  const seen=new Set();
  async function expand(source){let result=source.replace(/\r\n/g,'\n');for(const match of [...result.matchAll(include)].reverse()){
    const base=match[2]?'tavern-plugin/lib/domain':'tavern-plugin/src/client';
    const relative=path.posix.normalize(base+'/'+match[3]);
    if(!relative.startsWith(base+'/')||seen.has(relative))throw new Error('客户端 include 越界或重复：'+relative);seen.add(relative);
    let fragment=output.get(relative)??await readFile(path.join(root,relative),'utf8');
    if(match[2])fragment=fragment.replace(/^export \{[^}]+\};?$/gm,'');
    fragment=await expand(fragment);
    const indented=fragment.trimEnd().split('\n').map(line=>line?match[1]+line:'').join('\n');
    result=result.slice(0,match.index)+indented+result.slice(match.index+match[0].length);
  }return result;}
  const brand={};for(const name of ['logo','lockup','lockup-dark']){const svg=await readFile(path.join(root,'tavern-plugin/lib/client-assets',name+'.svg'),'utf8');brand[name]='data:image/svg+xml,'+encodeURIComponent(svg.replace(/\s*\n\s*/g,''));}
  const css=await readFile(path.join(root,'tavern-plugin/lib/client-assets/tavern.css'),'utf8');
  const expanded=await expand(output.get('tavern-plugin/src/client/main.js'));
  const client='// Generated by pnpm build:client; do not edit directly.\n'+expanded.replace('__TAVERN_BUNDLED_CSS__',()=>JSON.stringify(css)).replace('__TAVERN_BRAND_URLS__',()=>JSON.stringify(brand)).trimEnd()+'\n';
  new vm.Script(client,{filename:'tavern-plugin/lib/client.js'});
  original.set('tavern-plugin/lib/client.js',await readFile(path.join(root,'tavern-plugin/lib/client.js')));output.set('tavern-plugin/lib/client.js',client);
  if(!apply)console.log('检查通过：所有桥接锚点及完整客户端语法有效；未修改文件。加入 --apply 安装。');
  else{
    await mkdir(backup,{recursive:true});
    const files=[];
    for(const [file,data] of output){const old=original.get(file);if(old){await mkdir(path.dirname(path.join(backup,file)),{recursive:true});await writeFile(path.join(backup,file),old);}files.push({file,existed:old!==null,originalHash:old?hash(old):null,installedHash:hash(data)});}
    const changed=[];
    try{
      for(const [file,data] of output){await atomic(path.join(root,file),data);changed.push(file);}
      await atomic(manifestPath,JSON.stringify({version:1,root,files},null,2));
    }catch(error){for(const file of changed.reverse()){const old=original.get(file);if(old)await atomic(path.join(root,file),old);else await unlink(path.join(root,file));}throw error;}
    console.log('已安装桥接并保存带哈希的源码备份。未修改存档、Profile 或插件启用配置。');
  }
}
